version: '3.8'

services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "9090:8000"
    depends_on:
      - db
    environment:
      DJANGO_DB: postgresql
      DB_NAME: blogapp
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blogapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "blogapp", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
